<?php
/**
 * ComHivextApiServerEnvironmentResponseExtDomainResponseExtDomainSslCert
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jelastic API docs
 *
 * lets developers to automate a set of actions required for application lifecycle and extend our platform functionality by combining with other services. Using our API you can programmatically create environments, deploy apps and perform other tasks that could be earlier accomplished only via Jelastic dashboard but not limited to them.  Jelastic API follows REST principles. REST API determines a set of functions which can be requested by a developer, who then receives a response. The interaction is performed via HTTP protocol. The advantage of such method is a wide extension of the HTTP protocol. That's why REST API can be used from almost any programming language.
 *
 * The version of the OpenAPI document: 8.0.2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ComHivextApiServerEnvironmentResponseExtDomainResponseExtDomainSslCert Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ComHivextApiServerEnvironmentResponseExtDomainResponseExtDomainSslCert implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'com_hivext_api_server_environment_response_ExtDomainResponse_extDomain_sslCert';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'uid' => 'int',
        'isDeleted' => 'bool',
        'sslType' => 'string',
        'issuedBy' => 'string',
        'intermediate' => 'string',
        'useObjectHash' => 'bool',
        'domains' => 'string',
        'cert' => 'string',
        'id' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'uid' => 'int32',
        'isDeleted' => null,
        'sslType' => null,
        'issuedBy' => null,
        'intermediate' => null,
        'useObjectHash' => null,
        'domains' => null,
        'cert' => null,
        'id' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'uid' => false,
		'isDeleted' => false,
		'sslType' => false,
		'issuedBy' => false,
		'intermediate' => false,
		'useObjectHash' => false,
		'domains' => false,
		'cert' => false,
		'id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'uid' => 'uid',
        'isDeleted' => 'isDeleted',
        'sslType' => 'sslType',
        'issuedBy' => 'issuedBy',
        'intermediate' => 'intermediate',
        'useObjectHash' => 'useObjectHash',
        'domains' => 'domains',
        'cert' => 'cert',
        'id' => 'id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'uid' => 'setUid',
        'isDeleted' => 'setIsDeleted',
        'sslType' => 'setSslType',
        'issuedBy' => 'setIssuedBy',
        'intermediate' => 'setIntermediate',
        'useObjectHash' => 'setUseObjectHash',
        'domains' => 'setDomains',
        'cert' => 'setCert',
        'id' => 'setId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'uid' => 'getUid',
        'isDeleted' => 'getIsDeleted',
        'sslType' => 'getSslType',
        'issuedBy' => 'getIssuedBy',
        'intermediate' => 'getIntermediate',
        'useObjectHash' => 'getUseObjectHash',
        'domains' => 'getDomains',
        'cert' => 'getCert',
        'id' => 'getId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const SSL_TYPE_CUSTOM_0 = 'CUSTOM(0)';
    public const SSL_TYPE_LETSENCRYPT_1 = 'LETSENCRYPT(1)';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSslTypeAllowableValues()
    {
        return [
            self::SSL_TYPE_CUSTOM_0,
            self::SSL_TYPE_LETSENCRYPT_1,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('uid', $data ?? [], null);
        $this->setIfExists('isDeleted', $data ?? [], null);
        $this->setIfExists('sslType', $data ?? [], null);
        $this->setIfExists('issuedBy', $data ?? [], null);
        $this->setIfExists('intermediate', $data ?? [], null);
        $this->setIfExists('useObjectHash', $data ?? [], null);
        $this->setIfExists('domains', $data ?? [], null);
        $this->setIfExists('cert', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['uid']) && ($this->container['uid'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'uid', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['uid']) && ($this->container['uid'] < -2147483648)) {
            $invalidProperties[] = "invalid value for 'uid', must be bigger than or equal to -2147483648.";
        }

        $allowedValues = $this->getSslTypeAllowableValues();
        if (!is_null($this->container['sslType']) && !in_array($this->container['sslType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'sslType', must be one of '%s'",
                $this->container['sslType'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['issuedBy']) && (mb_strlen($this->container['issuedBy']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'issuedBy', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['issuedBy']) && !preg_match("/(.*){0,2147483647}/", $this->container['issuedBy'])) {
            $invalidProperties[] = "invalid value for 'issuedBy', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        if (!is_null($this->container['intermediate']) && (mb_strlen($this->container['intermediate']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'intermediate', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['intermediate']) && !preg_match("/(.*){0,2147483647}/", $this->container['intermediate'])) {
            $invalidProperties[] = "invalid value for 'intermediate', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        if (!is_null($this->container['domains']) && (mb_strlen($this->container['domains']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'domains', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['domains']) && !preg_match("/(.*){0,2147483647}/", $this->container['domains'])) {
            $invalidProperties[] = "invalid value for 'domains', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        if (!is_null($this->container['cert']) && (mb_strlen($this->container['cert']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'cert', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['cert']) && !preg_match("/(.*){0,2147483647}/", $this->container['cert'])) {
            $invalidProperties[] = "invalid value for 'cert', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        if (!is_null($this->container['id']) && ($this->container['id'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'id', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['id']) && ($this->container['id'] < -2147483648)) {
            $invalidProperties[] = "invalid value for 'id', must be bigger than or equal to -2147483648.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets uid
     *
     * @return int|null
     */
    public function getUid()
    {
        return $this->container['uid'];
    }

    /**
     * Sets uid
     *
     * @param int|null $uid uid
     *
     * @return self
     */
    public function setUid($uid)
    {

        if (!is_null($uid) && ($uid > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $uid when calling ComHivextApiServerEnvironmentResponseExtDomainResponseExtDomainSslCert., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($uid) && ($uid < -2147483648)) {
            throw new \InvalidArgumentException('invalid value for $uid when calling ComHivextApiServerEnvironmentResponseExtDomainResponseExtDomainSslCert., must be bigger than or equal to -2147483648.');
        }


        if (is_null($uid)) {
            throw new \InvalidArgumentException('non-nullable uid cannot be null');
        }

        $this->container['uid'] = $uid;

        return $this;
    }

    /**
     * Gets isDeleted
     *
     * @return bool|null
     */
    public function getIsDeleted()
    {
        return $this->container['isDeleted'];
    }

    /**
     * Sets isDeleted
     *
     * @param bool|null $isDeleted isDeleted
     *
     * @return self
     */
    public function setIsDeleted($isDeleted)
    {

        if (is_null($isDeleted)) {
            throw new \InvalidArgumentException('non-nullable isDeleted cannot be null');
        }

        $this->container['isDeleted'] = $isDeleted;

        return $this;
    }

    /**
     * Gets sslType
     *
     * @return string|null
     */
    public function getSslType()
    {
        return $this->container['sslType'];
    }

    /**
     * Sets sslType
     *
     * @param string|null $sslType sslType
     *
     * @return self
     */
    public function setSslType($sslType)
    {
        $allowedValues = $this->getSslTypeAllowableValues();
        if (!is_null($sslType) && !in_array($sslType, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'sslType', must be one of '%s'",
                    $sslType,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($sslType)) {
            throw new \InvalidArgumentException('non-nullable sslType cannot be null');
        }

        $this->container['sslType'] = $sslType;

        return $this;
    }

    /**
     * Gets issuedBy
     *
     * @return string|null
     */
    public function getIssuedBy()
    {
        return $this->container['issuedBy'];
    }

    /**
     * Sets issuedBy
     *
     * @param string|null $issuedBy issuedBy
     *
     * @return self
     */
    public function setIssuedBy($issuedBy)
    {
        if (!is_null($issuedBy) && (mb_strlen($issuedBy) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $issuedBy when calling ComHivextApiServerEnvironmentResponseExtDomainResponseExtDomainSslCert., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($issuedBy) && (!preg_match("/(.*){0,2147483647}/", $issuedBy))) {
            throw new \InvalidArgumentException("invalid value for \$issuedBy when calling ComHivextApiServerEnvironmentResponseExtDomainResponseExtDomainSslCert., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($issuedBy)) {
            throw new \InvalidArgumentException('non-nullable issuedBy cannot be null');
        }

        $this->container['issuedBy'] = $issuedBy;

        return $this;
    }

    /**
     * Gets intermediate
     *
     * @return string|null
     */
    public function getIntermediate()
    {
        return $this->container['intermediate'];
    }

    /**
     * Sets intermediate
     *
     * @param string|null $intermediate intermediate
     *
     * @return self
     */
    public function setIntermediate($intermediate)
    {
        if (!is_null($intermediate) && (mb_strlen($intermediate) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $intermediate when calling ComHivextApiServerEnvironmentResponseExtDomainResponseExtDomainSslCert., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($intermediate) && (!preg_match("/(.*){0,2147483647}/", $intermediate))) {
            throw new \InvalidArgumentException("invalid value for \$intermediate when calling ComHivextApiServerEnvironmentResponseExtDomainResponseExtDomainSslCert., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($intermediate)) {
            throw new \InvalidArgumentException('non-nullable intermediate cannot be null');
        }

        $this->container['intermediate'] = $intermediate;

        return $this;
    }

    /**
     * Gets useObjectHash
     *
     * @return bool|null
     */
    public function getUseObjectHash()
    {
        return $this->container['useObjectHash'];
    }

    /**
     * Sets useObjectHash
     *
     * @param bool|null $useObjectHash useObjectHash
     *
     * @return self
     */
    public function setUseObjectHash($useObjectHash)
    {

        if (is_null($useObjectHash)) {
            throw new \InvalidArgumentException('non-nullable useObjectHash cannot be null');
        }

        $this->container['useObjectHash'] = $useObjectHash;

        return $this;
    }

    /**
     * Gets domains
     *
     * @return string|null
     */
    public function getDomains()
    {
        return $this->container['domains'];
    }

    /**
     * Sets domains
     *
     * @param string|null $domains domains
     *
     * @return self
     */
    public function setDomains($domains)
    {
        if (!is_null($domains) && (mb_strlen($domains) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $domains when calling ComHivextApiServerEnvironmentResponseExtDomainResponseExtDomainSslCert., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($domains) && (!preg_match("/(.*){0,2147483647}/", $domains))) {
            throw new \InvalidArgumentException("invalid value for \$domains when calling ComHivextApiServerEnvironmentResponseExtDomainResponseExtDomainSslCert., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($domains)) {
            throw new \InvalidArgumentException('non-nullable domains cannot be null');
        }

        $this->container['domains'] = $domains;

        return $this;
    }

    /**
     * Gets cert
     *
     * @return string|null
     */
    public function getCert()
    {
        return $this->container['cert'];
    }

    /**
     * Sets cert
     *
     * @param string|null $cert cert
     *
     * @return self
     */
    public function setCert($cert)
    {
        if (!is_null($cert) && (mb_strlen($cert) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $cert when calling ComHivextApiServerEnvironmentResponseExtDomainResponseExtDomainSslCert., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($cert) && (!preg_match("/(.*){0,2147483647}/", $cert))) {
            throw new \InvalidArgumentException("invalid value for \$cert when calling ComHivextApiServerEnvironmentResponseExtDomainResponseExtDomainSslCert., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($cert)) {
            throw new \InvalidArgumentException('non-nullable cert cannot be null');
        }

        $this->container['cert'] = $cert;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {

        if (!is_null($id) && ($id > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $id when calling ComHivextApiServerEnvironmentResponseExtDomainResponseExtDomainSslCert., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($id) && ($id < -2147483648)) {
            throw new \InvalidArgumentException('invalid value for $id when calling ComHivextApiServerEnvironmentResponseExtDomainResponseExtDomainSslCert., must be bigger than or equal to -2147483648.');
        }


        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }

        $this->container['id'] = $id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


