<?php
/**
 * ComHivextApiServerEnvironmentResponseBuildProjectResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jelastic API docs
 *
 * lets developers to automate a set of actions required for application lifecycle and extend our platform functionality by combining with other services. Using our API you can programmatically create environments, deploy apps and perform other tasks that could be earlier accomplished only via Jelastic dashboard but not limited to them.  Jelastic API follows REST principles. REST API determines a set of functions which can be requested by a developer, who then receives a response. The interaction is performed via HTTP protocol. The advantage of such method is a wide extension of the HTTP protocol. That's why REST API can be used from almost any programming language.
 *
 * The version of the OpenAPI document: 8.0.2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ComHivextApiServerEnvironmentResponseBuildProjectResponse Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ComHivextApiServerEnvironmentResponseBuildProjectResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'com.hivext.api.server.environment.response.BuildProjectResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'autoResolveConflict' => 'bool',
        'autoupdate' => 'bool',
        'branch' => 'string',
        'context' => 'string',
        'env' => 'string',
        'error' => 'string',
        'hash' => 'string',
        'hooks' => 'string',
        'id' => 'int',
        'interval' => 'string',
        'login' => 'string',
        'name' => 'string',
        'path' => 'string',
        'reason' => 'int',
        'repoHash' => 'string',
        'result' => 'int',
        'source' => 'string',
        'targetNodeGroup' => 'string',
        'type' => 'string',
        'workDir' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'autoResolveConflict' => null,
        'autoupdate' => null,
        'branch' => null,
        'context' => null,
        'env' => null,
        'error' => null,
        'hash' => null,
        'hooks' => null,
        'id' => 'int32',
        'interval' => null,
        'login' => null,
        'name' => null,
        'path' => null,
        'reason' => 'int32',
        'repoHash' => null,
        'result' => 'int32',
        'source' => null,
        'targetNodeGroup' => null,
        'type' => null,
        'workDir' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'autoResolveConflict' => false,
		'autoupdate' => false,
		'branch' => false,
		'context' => false,
		'env' => false,
		'error' => false,
		'hash' => false,
		'hooks' => false,
		'id' => false,
		'interval' => false,
		'login' => false,
		'name' => false,
		'path' => false,
		'reason' => false,
		'repoHash' => false,
		'result' => false,
		'source' => false,
		'targetNodeGroup' => false,
		'type' => false,
		'workDir' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'autoResolveConflict' => 'autoResolveConflict',
        'autoupdate' => 'autoupdate',
        'branch' => 'branch',
        'context' => 'context',
        'env' => 'env',
        'error' => 'error',
        'hash' => 'hash',
        'hooks' => 'hooks',
        'id' => 'id',
        'interval' => 'interval',
        'login' => 'login',
        'name' => 'name',
        'path' => 'path',
        'reason' => 'reason',
        'repoHash' => 'repoHash',
        'result' => 'result',
        'source' => 'source',
        'targetNodeGroup' => 'targetNodeGroup',
        'type' => 'type',
        'workDir' => 'workDir'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'autoResolveConflict' => 'setAutoResolveConflict',
        'autoupdate' => 'setAutoupdate',
        'branch' => 'setBranch',
        'context' => 'setContext',
        'env' => 'setEnv',
        'error' => 'setError',
        'hash' => 'setHash',
        'hooks' => 'setHooks',
        'id' => 'setId',
        'interval' => 'setInterval',
        'login' => 'setLogin',
        'name' => 'setName',
        'path' => 'setPath',
        'reason' => 'setReason',
        'repoHash' => 'setRepoHash',
        'result' => 'setResult',
        'source' => 'setSource',
        'targetNodeGroup' => 'setTargetNodeGroup',
        'type' => 'setType',
        'workDir' => 'setWorkDir'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'autoResolveConflict' => 'getAutoResolveConflict',
        'autoupdate' => 'getAutoupdate',
        'branch' => 'getBranch',
        'context' => 'getContext',
        'env' => 'getEnv',
        'error' => 'getError',
        'hash' => 'getHash',
        'hooks' => 'getHooks',
        'id' => 'getId',
        'interval' => 'getInterval',
        'login' => 'getLogin',
        'name' => 'getName',
        'path' => 'getPath',
        'reason' => 'getReason',
        'repoHash' => 'getRepoHash',
        'result' => 'getResult',
        'source' => 'getSource',
        'targetNodeGroup' => 'getTargetNodeGroup',
        'type' => 'getType',
        'workDir' => 'getWorkDir'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('autoResolveConflict', $data ?? [], null);
        $this->setIfExists('autoupdate', $data ?? [], null);
        $this->setIfExists('branch', $data ?? [], null);
        $this->setIfExists('context', $data ?? [], null);
        $this->setIfExists('env', $data ?? [], null);
        $this->setIfExists('error', $data ?? [], null);
        $this->setIfExists('hash', $data ?? [], null);
        $this->setIfExists('hooks', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('interval', $data ?? [], null);
        $this->setIfExists('login', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('path', $data ?? [], null);
        $this->setIfExists('reason', $data ?? [], null);
        $this->setIfExists('repoHash', $data ?? [], null);
        $this->setIfExists('result', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('targetNodeGroup', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('workDir', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['branch']) && (mb_strlen($this->container['branch']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'branch', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['branch']) && !preg_match("/(.*){0,2147483647}/", $this->container['branch'])) {
            $invalidProperties[] = "invalid value for 'branch', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        if (!is_null($this->container['context']) && (mb_strlen($this->container['context']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'context', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['context']) && !preg_match("/(.*){0,2147483647}/", $this->container['context'])) {
            $invalidProperties[] = "invalid value for 'context', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        if (!is_null($this->container['env']) && (mb_strlen($this->container['env']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'env', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['env']) && !preg_match("/(.*){0,2147483647}/", $this->container['env'])) {
            $invalidProperties[] = "invalid value for 'env', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        if (!is_null($this->container['error']) && (mb_strlen($this->container['error']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'error', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['error']) && !preg_match("/(.*){0,2147483647}/", $this->container['error'])) {
            $invalidProperties[] = "invalid value for 'error', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        if (!is_null($this->container['hash']) && (mb_strlen($this->container['hash']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'hash', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['hash']) && !preg_match("/(.*){0,2147483647}/", $this->container['hash'])) {
            $invalidProperties[] = "invalid value for 'hash', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        if (!is_null($this->container['hooks']) && (mb_strlen($this->container['hooks']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'hooks', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['hooks']) && !preg_match("/(.*){0,2147483647}/", $this->container['hooks'])) {
            $invalidProperties[] = "invalid value for 'hooks', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        if (!is_null($this->container['id']) && ($this->container['id'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'id', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['id']) && ($this->container['id'] < -2147483648)) {
            $invalidProperties[] = "invalid value for 'id', must be bigger than or equal to -2147483648.";
        }

        if (!is_null($this->container['interval']) && (mb_strlen($this->container['interval']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'interval', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['interval']) && !preg_match("/(.*){0,2147483647}/", $this->container['interval'])) {
            $invalidProperties[] = "invalid value for 'interval', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        if (!is_null($this->container['login']) && (mb_strlen($this->container['login']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'login', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['login']) && !preg_match("/(.*){0,2147483647}/", $this->container['login'])) {
            $invalidProperties[] = "invalid value for 'login', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        if (!is_null($this->container['name']) && (mb_strlen($this->container['name']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['name']) && !preg_match("/(.*){0,2147483647}/", $this->container['name'])) {
            $invalidProperties[] = "invalid value for 'name', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        if (!is_null($this->container['path']) && (mb_strlen($this->container['path']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'path', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['path']) && !preg_match("/(.*){0,2147483647}/", $this->container['path'])) {
            $invalidProperties[] = "invalid value for 'path', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        if (!is_null($this->container['reason']) && ($this->container['reason'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'reason', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['reason']) && ($this->container['reason'] < -2147483648)) {
            $invalidProperties[] = "invalid value for 'reason', must be bigger than or equal to -2147483648.";
        }

        if (!is_null($this->container['repoHash']) && (mb_strlen($this->container['repoHash']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'repoHash', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['repoHash']) && !preg_match("/(.*){0,2147483647}/", $this->container['repoHash'])) {
            $invalidProperties[] = "invalid value for 'repoHash', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        if (!is_null($this->container['result']) && ($this->container['result'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'result', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['result']) && ($this->container['result'] < -2147483648)) {
            $invalidProperties[] = "invalid value for 'result', must be bigger than or equal to -2147483648.";
        }

        if (!is_null($this->container['source']) && (mb_strlen($this->container['source']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'source', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['source']) && !preg_match("/(.*){0,2147483647}/", $this->container['source'])) {
            $invalidProperties[] = "invalid value for 'source', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        if (!is_null($this->container['targetNodeGroup']) && (mb_strlen($this->container['targetNodeGroup']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'targetNodeGroup', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['targetNodeGroup']) && !preg_match("/(.*){0,2147483647}/", $this->container['targetNodeGroup'])) {
            $invalidProperties[] = "invalid value for 'targetNodeGroup', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        if (!is_null($this->container['type']) && (mb_strlen($this->container['type']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'type', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['type']) && !preg_match("/(.*){0,2147483647}/", $this->container['type'])) {
            $invalidProperties[] = "invalid value for 'type', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        if (!is_null($this->container['workDir']) && (mb_strlen($this->container['workDir']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'workDir', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['workDir']) && !preg_match("/(.*){0,2147483647}/", $this->container['workDir'])) {
            $invalidProperties[] = "invalid value for 'workDir', must be conform to the pattern /(.*){0,2147483647}/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets autoResolveConflict
     *
     * @return bool|null
     */
    public function getAutoResolveConflict()
    {
        return $this->container['autoResolveConflict'];
    }

    /**
     * Sets autoResolveConflict
     *
     * @param bool|null $autoResolveConflict autoResolveConflict
     *
     * @return self
     */
    public function setAutoResolveConflict($autoResolveConflict)
    {

        if (is_null($autoResolveConflict)) {
            throw new \InvalidArgumentException('non-nullable autoResolveConflict cannot be null');
        }

        $this->container['autoResolveConflict'] = $autoResolveConflict;

        return $this;
    }

    /**
     * Gets autoupdate
     *
     * @return bool|null
     */
    public function getAutoupdate()
    {
        return $this->container['autoupdate'];
    }

    /**
     * Sets autoupdate
     *
     * @param bool|null $autoupdate autoupdate
     *
     * @return self
     */
    public function setAutoupdate($autoupdate)
    {

        if (is_null($autoupdate)) {
            throw new \InvalidArgumentException('non-nullable autoupdate cannot be null');
        }

        $this->container['autoupdate'] = $autoupdate;

        return $this;
    }

    /**
     * Gets branch
     *
     * @return string|null
     */
    public function getBranch()
    {
        return $this->container['branch'];
    }

    /**
     * Sets branch
     *
     * @param string|null $branch branch
     *
     * @return self
     */
    public function setBranch($branch)
    {
        if (!is_null($branch) && (mb_strlen($branch) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $branch when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($branch) && (!preg_match("/(.*){0,2147483647}/", $branch))) {
            throw new \InvalidArgumentException("invalid value for \$branch when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($branch)) {
            throw new \InvalidArgumentException('non-nullable branch cannot be null');
        }

        $this->container['branch'] = $branch;

        return $this;
    }

    /**
     * Gets context
     *
     * @return string|null
     */
    public function getContext()
    {
        return $this->container['context'];
    }

    /**
     * Sets context
     *
     * @param string|null $context context
     *
     * @return self
     */
    public function setContext($context)
    {
        if (!is_null($context) && (mb_strlen($context) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $context when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($context) && (!preg_match("/(.*){0,2147483647}/", $context))) {
            throw new \InvalidArgumentException("invalid value for \$context when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($context)) {
            throw new \InvalidArgumentException('non-nullable context cannot be null');
        }

        $this->container['context'] = $context;

        return $this;
    }

    /**
     * Gets env
     *
     * @return string|null
     */
    public function getEnv()
    {
        return $this->container['env'];
    }

    /**
     * Sets env
     *
     * @param string|null $env env
     *
     * @return self
     */
    public function setEnv($env)
    {
        if (!is_null($env) && (mb_strlen($env) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $env when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($env) && (!preg_match("/(.*){0,2147483647}/", $env))) {
            throw new \InvalidArgumentException("invalid value for \$env when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($env)) {
            throw new \InvalidArgumentException('non-nullable env cannot be null');
        }

        $this->container['env'] = $env;

        return $this;
    }

    /**
     * Gets error
     *
     * @return string|null
     */
    public function getError()
    {
        return $this->container['error'];
    }

    /**
     * Sets error
     *
     * @param string|null $error error
     *
     * @return self
     */
    public function setError($error)
    {
        if (!is_null($error) && (mb_strlen($error) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $error when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($error) && (!preg_match("/(.*){0,2147483647}/", $error))) {
            throw new \InvalidArgumentException("invalid value for \$error when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($error)) {
            throw new \InvalidArgumentException('non-nullable error cannot be null');
        }

        $this->container['error'] = $error;

        return $this;
    }

    /**
     * Gets hash
     *
     * @return string|null
     */
    public function getHash()
    {
        return $this->container['hash'];
    }

    /**
     * Sets hash
     *
     * @param string|null $hash hash
     *
     * @return self
     */
    public function setHash($hash)
    {
        if (!is_null($hash) && (mb_strlen($hash) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $hash when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($hash) && (!preg_match("/(.*){0,2147483647}/", $hash))) {
            throw new \InvalidArgumentException("invalid value for \$hash when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($hash)) {
            throw new \InvalidArgumentException('non-nullable hash cannot be null');
        }

        $this->container['hash'] = $hash;

        return $this;
    }

    /**
     * Gets hooks
     *
     * @return string|null
     */
    public function getHooks()
    {
        return $this->container['hooks'];
    }

    /**
     * Sets hooks
     *
     * @param string|null $hooks hooks
     *
     * @return self
     */
    public function setHooks($hooks)
    {
        if (!is_null($hooks) && (mb_strlen($hooks) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $hooks when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($hooks) && (!preg_match("/(.*){0,2147483647}/", $hooks))) {
            throw new \InvalidArgumentException("invalid value for \$hooks when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($hooks)) {
            throw new \InvalidArgumentException('non-nullable hooks cannot be null');
        }

        $this->container['hooks'] = $hooks;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {

        if (!is_null($id) && ($id > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $id when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($id) && ($id < -2147483648)) {
            throw new \InvalidArgumentException('invalid value for $id when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be bigger than or equal to -2147483648.');
        }


        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets interval
     *
     * @return string|null
     */
    public function getInterval()
    {
        return $this->container['interval'];
    }

    /**
     * Sets interval
     *
     * @param string|null $interval interval
     *
     * @return self
     */
    public function setInterval($interval)
    {
        if (!is_null($interval) && (mb_strlen($interval) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $interval when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($interval) && (!preg_match("/(.*){0,2147483647}/", $interval))) {
            throw new \InvalidArgumentException("invalid value for \$interval when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($interval)) {
            throw new \InvalidArgumentException('non-nullable interval cannot be null');
        }

        $this->container['interval'] = $interval;

        return $this;
    }

    /**
     * Gets login
     *
     * @return string|null
     */
    public function getLogin()
    {
        return $this->container['login'];
    }

    /**
     * Sets login
     *
     * @param string|null $login login
     *
     * @return self
     */
    public function setLogin($login)
    {
        if (!is_null($login) && (mb_strlen($login) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $login when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($login) && (!preg_match("/(.*){0,2147483647}/", $login))) {
            throw new \InvalidArgumentException("invalid value for \$login when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($login)) {
            throw new \InvalidArgumentException('non-nullable login cannot be null');
        }

        $this->container['login'] = $login;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (!is_null($name) && (mb_strlen($name) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $name when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($name) && (!preg_match("/(.*){0,2147483647}/", $name))) {
            throw new \InvalidArgumentException("invalid value for \$name when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets path
     *
     * @return string|null
     */
    public function getPath()
    {
        return $this->container['path'];
    }

    /**
     * Sets path
     *
     * @param string|null $path path
     *
     * @return self
     */
    public function setPath($path)
    {
        if (!is_null($path) && (mb_strlen($path) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $path when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($path) && (!preg_match("/(.*){0,2147483647}/", $path))) {
            throw new \InvalidArgumentException("invalid value for \$path when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($path)) {
            throw new \InvalidArgumentException('non-nullable path cannot be null');
        }

        $this->container['path'] = $path;

        return $this;
    }

    /**
     * Gets reason
     *
     * @return int|null
     */
    public function getReason()
    {
        return $this->container['reason'];
    }

    /**
     * Sets reason
     *
     * @param int|null $reason reason
     *
     * @return self
     */
    public function setReason($reason)
    {

        if (!is_null($reason) && ($reason > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $reason when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($reason) && ($reason < -2147483648)) {
            throw new \InvalidArgumentException('invalid value for $reason when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be bigger than or equal to -2147483648.');
        }


        if (is_null($reason)) {
            throw new \InvalidArgumentException('non-nullable reason cannot be null');
        }

        $this->container['reason'] = $reason;

        return $this;
    }

    /**
     * Gets repoHash
     *
     * @return string|null
     */
    public function getRepoHash()
    {
        return $this->container['repoHash'];
    }

    /**
     * Sets repoHash
     *
     * @param string|null $repoHash repoHash
     *
     * @return self
     */
    public function setRepoHash($repoHash)
    {
        if (!is_null($repoHash) && (mb_strlen($repoHash) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $repoHash when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($repoHash) && (!preg_match("/(.*){0,2147483647}/", $repoHash))) {
            throw new \InvalidArgumentException("invalid value for \$repoHash when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($repoHash)) {
            throw new \InvalidArgumentException('non-nullable repoHash cannot be null');
        }

        $this->container['repoHash'] = $repoHash;

        return $this;
    }

    /**
     * Gets result
     *
     * @return int|null
     */
    public function getResult()
    {
        return $this->container['result'];
    }

    /**
     * Sets result
     *
     * @param int|null $result result
     *
     * @return self
     */
    public function setResult($result)
    {

        if (!is_null($result) && ($result > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $result when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($result) && ($result < -2147483648)) {
            throw new \InvalidArgumentException('invalid value for $result when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be bigger than or equal to -2147483648.');
        }


        if (is_null($result)) {
            throw new \InvalidArgumentException('non-nullable result cannot be null');
        }

        $this->container['result'] = $result;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string|null
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string|null $source source
     *
     * @return self
     */
    public function setSource($source)
    {
        if (!is_null($source) && (mb_strlen($source) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $source when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($source) && (!preg_match("/(.*){0,2147483647}/", $source))) {
            throw new \InvalidArgumentException("invalid value for \$source when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }

        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets targetNodeGroup
     *
     * @return string|null
     */
    public function getTargetNodeGroup()
    {
        return $this->container['targetNodeGroup'];
    }

    /**
     * Sets targetNodeGroup
     *
     * @param string|null $targetNodeGroup targetNodeGroup
     *
     * @return self
     */
    public function setTargetNodeGroup($targetNodeGroup)
    {
        if (!is_null($targetNodeGroup) && (mb_strlen($targetNodeGroup) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $targetNodeGroup when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($targetNodeGroup) && (!preg_match("/(.*){0,2147483647}/", $targetNodeGroup))) {
            throw new \InvalidArgumentException("invalid value for \$targetNodeGroup when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($targetNodeGroup)) {
            throw new \InvalidArgumentException('non-nullable targetNodeGroup cannot be null');
        }

        $this->container['targetNodeGroup'] = $targetNodeGroup;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (!is_null($type) && (mb_strlen($type) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $type when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($type) && (!preg_match("/(.*){0,2147483647}/", $type))) {
            throw new \InvalidArgumentException("invalid value for \$type when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }

        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets workDir
     *
     * @return string|null
     */
    public function getWorkDir()
    {
        return $this->container['workDir'];
    }

    /**
     * Sets workDir
     *
     * @param string|null $workDir workDir
     *
     * @return self
     */
    public function setWorkDir($workDir)
    {
        if (!is_null($workDir) && (mb_strlen($workDir) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $workDir when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($workDir) && (!preg_match("/(.*){0,2147483647}/", $workDir))) {
            throw new \InvalidArgumentException("invalid value for \$workDir when calling ComHivextApiServerEnvironmentResponseBuildProjectResponse., must conform to the pattern /(.*){0,2147483647}/.");
        }


        if (is_null($workDir)) {
            throw new \InvalidArgumentException('non-nullable workDir cannot be null');
        }

        $this->container['workDir'] = $workDir;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


