<?php
/**
 * AppServiceApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jelastic API docs
 *
 * lets developers to automate a set of actions required for application lifecycle and extend our platform functionality by combining with other services. Using our API you can programmatically create environments, deploy apps and perform other tasks that could be earlier accomplished only via Jelastic dashboard but not limited to them.  Jelastic API follows REST principles. REST API determines a set of functions which can be requested by a developer, who then receives a response. The interaction is performed via HTTP protocol. The advantage of such method is a wide extension of the HTTP protocol. That's why REST API can be used from almost any programming language.
 *
 * The version of the OpenAPI document: 8.0.2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AppServiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AppServiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for marketplaceAppRestAddappPost
     *
     * .
     *
     */
    public function testMarketplaceAppRestAddappPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for marketplaceAppRestDeleteappPost
     *
     * .
     *
     */
    public function testMarketplaceAppRestDeleteappPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for marketplaceAppRestEditappPost
     *
     * .
     *
     */
    public function testMarketplaceAppRestEditappPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for marketplaceAppRestGetaddonlistPost
     *
     * .
     *
     */
    public function testMarketplaceAppRestGetaddonlistPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for marketplaceAppRestGetappinfoPost
     *
     * .
     *
     */
    public function testMarketplaceAppRestGetappinfoPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for marketplaceAppRestGetcategoriesPost
     *
     * .
     *
     */
    public function testMarketplaceAppRestGetcategoriesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for marketplaceAppRestGetchecksumPost
     *
     * .
     *
     */
    public function testMarketplaceAppRestGetchecksumPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for marketplaceAppRestGetlistPost
     *
     * .
     *
     */
    public function testMarketplaceAppRestGetlistPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for marketplaceAppRestInstallPost
     *
     * .
     *
     */
    public function testMarketplaceAppRestInstallPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for marketplaceAppRestInstalladdonPost
     *
     * .
     *
     */
    public function testMarketplaceAppRestInstalladdonPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
